# Generated by Django 3.2.8 on 2022-01-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_infos',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('specialist_in', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='doctor',
            field=models.ForeignKey(default='', max_length=550, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor_infos'),
        ),
        migrations.DeleteModel(
            name='doctor_info',
        ),
    ]
