# Generated by Django 3.2.8 on 2022-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_info_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduled_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(default='', max_length=150)),
                ('patient', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('reason', models.CharField(default='', max_length=60)),
                ('symptoms', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=320)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
    ]
